import type { Metadata } from "next";
import { basisgrotesque } from "@/styles/font";
import "../styles/tailwind.css"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={basisgrotesque.className}>{children}</body>
    </html>
  );
}
